version: '3.8'
services:
  app:
    image: anderskambenders/nodejs2024q1-service-app
    restart: always
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - nodejs2024q1
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    command: ["npm", "run", "migrate:start:dev"]

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: ["postgres", "-c", "logging_collector=true", "-c", "log_statement=all"]
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - nodejs2024q1
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminuser -d homelibdb"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s

  nest_test_pgadmin:
    container_name: nest_test_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_test@admin.com
      PGADMIN_DEFAULT_PASSWORD: nest_test
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/www/nest_test/docker-volumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - nodejs2024q1
    restart: unless-stopped

networks:
  nodejs2024q1:
    driver: bridge

volumes:
  postgres:
  pgadmin: